spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update

#docker run --name postgres -e POSTGRES_PASSWORD=12345 -e POSTGRES_DB=postgres -d -p 5432:5432 postgres